project:
  type: website
  output-dir: docs
website:
  title: "Jay's Happy Place!"
  favicon: images/favicon.png
  navbar:
    title: false
    right:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd
      - text: Blog
        href: posts.qmd
      - text: Resources
        href: resources.qmd
format: 
  html: 
    theme: styles.scss
    toc: true
    page-layout: full
    mainfont: Nunito