project:
  type: website
  output-dir: docs

website:
  title: "Jay's Happy Place!"
  favicon: images/favicon.png
  navbar:
    title: false
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - posts.qmd
      - href: resources.qmd
        text: Resources

format: 
  html: 
    theme: styles.scss
    toc: true
    page-layout: full
    mainfont: Nunito